server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: CampusNews
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campusnews?characterEncoding=utf8&useSSL=true
    username: root
    password: root
logging.level.team: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.agile.campusnews.app.model
wechat:
  miniapp:
    appid: wxaa5d5902c49a521c
    secret: 0b332b84919cfd0f0f000c0e47d5d0a6
fileForTarget: E:\Desktop\project\CampusNews\file