server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: CampusNews
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campusnews?characterEncoding=utf8&useSSL=true
    username: root
    password: root
  thymeleaf:
        mode: LEGACYHTML5
        encoding: UTF-8
        cache: false #开发时关闭缓存,不然没法看到实时页面
        prefix: classpath:/templates
logging.level.team: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.agile.campusnews.data.model
wechat:
  miniapp:
    appid: wx8d6c8552cc90aac4
    secret: 9c71bcc8cee3f488122de87e10cfa0b3
fileForTarget: D:\Desktop\PROJECT\CampusNews\fileaaaaa